In [1]:
import pandas as pd

In [3]:
netflix = pd.read_csv("netflix.csv")

In [4]:
netflix

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [5]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sov_no          6234 non-null   int64
 1   tipi            6234 non-null   object
 2   baslik          6234 non-null   object
 3   yonetmen        4265 non-null   object
 4   oyuncular       5664 non-null   object
 5   ulke            5758 non-null   object
 6   eklenme_tarihi  6223 non-null   object
 7   cikis_tarihi    6234 non-null   int64
 8   sure            6234 non-null   object
 9   kategori        6234 non-null   object
 10  aciklama        6234 non-null   object
dtypes: int64(2), object(9)
memory usage: 535.9+ KB

In [6]:
netflix.dropna()

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...
6,70304989,Movie,Automata,Gabe Ibáñez,"Antonio Banderas, Dylan McDermott, Melanie Gri...","Bulgaria, United States, Spain, Canada","September 8, 2017",2014,110 min,"International Movies, Sci-Fi & Fantasy, Thrillers","In a dystopian future, an insurance adjuster f..."
7,80164077,Movie,Fabrizio Copano: Solo pienso en mi,"Rodrigo Toro, Francisco Schultz",Fabrizio Copano,Chile,"September 8, 2017",2017,60 min,Stand-Up Comedy,Fabrizio Copano takes audience participation t...
9,70304990,Movie,Good People,Henrik Ruben Genz,"James Franco, Kate Hudson, Tom Wilkinson, Omar...","United States, United Kingdom, Denmark, Sweden","September 8, 2017",2014,90 min,"Action & Adventure, Thrillers",A struggling couple can't believe their luck w...
...,...,...,...,...,...,...,...,...,...,...,...
6142,80063224,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"August 30, 2019",2019,7 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
6158,80164216,TV Show,Miraculous: Tales of Ladybug & Cat Noir,Thomas Astruc,"Cristina Vee, Bryce Papenbrook, Keith Silverst...","France, South Korea, Japan","August 2, 2019",2018,4 Seasons,"Kids' TV, TV Action & Adventure","When Paris is in peril, Marinette becomes Lady..."
6167,80115328,TV Show,Sacred Games,"Vikramaditya Motwane, Anurag Kashyap","Saif Ali Khan, Nawazuddin Siddiqui, Radhika Ap...","India, United States","August 15, 2019",2019,2 Seasons,"Crime TV Shows, International TV Shows, TV Dramas",A link in their pasts leads an honest cop to a...
6182,80176842,TV Show,Men on a Mission,Jung-ah Im,"Ho-dong Kang, Soo-geun Lee, Sang-min Lee, Youn...",South Korea,"April 9, 2019",2019,4 Seasons,"International TV Shows, Korean TV Shows, Stand...",Male celebs play make-believe as high schooler...
6213,80126599,TV Show,Leyla and Mecnun,Onur Ünlü,"Ali Atay, Melis Birkan, Serkan Keskin, Ahmet M...",Turkey,"April 15, 2017",2014,3 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Destiny brings Mecnun and Leyla together as ne...

In [7]:
netflix.dropna(how="all")

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [8]:

netflix.dropna(axis="columns")

,sov_no,tipi,baslik,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,2015,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,2016,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,2016,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,2013,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,2003,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [16]:
#NULL DEĞERLERİ DOLDURMA

In [17]:
netflix.fillna(value="-" , inplace=True)

In [18]:
netflix["yonetmen"].fillna("Yönetmen Bilimiyor" , inplace=True)

In [19]:
netflix

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,-,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,-,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,-,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,-,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,-,2015,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,-,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,-,2016,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,-,-,-,-,2016,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,-,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,-,2013,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,-,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,-,2003,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [20]:

netflix = pd.read_csv("netflix.csv")

In [21]:
netflix

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,99 min,Comedies,When nerdy high schooler Dani finally attracts...
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6230,70286564,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,60 min,Movies,Nursery rhymes and original music for children...
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,NaN,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
6233,70153404,TV Show,Friends,NaN,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...

In [23]:
netflix.sort_values("cikis_tarihi" ,ascending=False)

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
3467,81011449,TV Show,Medical Police,NaN,"Erinn Hayes, Rob Huebel, Malin Akerman, Rob Co...",United States,"January 10, 2020",2020,1 Season,"Crime TV Shows, TV Action & Adventure, TV Come...",Doctors Owen Maestro and Lola Spratt leave Chi...
3249,81006825,Movie,All the Freckles in the World,Yibrán Asuad,"Hánssel Casillas, Loreto Peralta, Andrea Sutto...",Mexico,"January 3, 2020",2020,90 min,"Comedies, International Movies, Romantic Movies",Thirteen-year-old José Miguel is immune to 199...
3220,80997687,TV Show,Dracula,NaN,"Claes Bang, Dolly Wells, John Heffernan",United Kingdom,"January 4, 2020",2020,1 Season,"British TV Shows, International TV Shows, TV D...",The Count Dracula legend transforms with new t...
3427,81060049,Movie,Leslie Jones: Time Machine,"David Benioff, D.B. Weiss",Leslie Jones,United States,"January 14, 2020",2020,66 min,Stand-Up Comedy,From trying to seduce Prince to battling sleep...
3436,80239306,TV Show,The Healing Powers of Dude,NaN,"Jace Chapman, Larisa Oleynik, Tom Everett Scot...",NaN,"January 13, 2020",2020,1 Season,"Kids' TV, TV Comedies, TV Dramas",When an 11-year-old boy with social anxiety di...
...,...,...,...,...,...,...,...,...,...,...,...
2023,70013050,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
2022,80119186,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,61 min,"Classic Movies, Documentaries",This World War II-era training film dramatizes...
2013,60027942,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
2011,60027945,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
4292,81030762,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,1 Season,TV Shows,This collection restores films from women who ...

In [24]:


netflix.sort_values("ulke" )

,sov_no,tipi,baslik,yonetmen,oyuncular,ulke,eklenme_tarihi,cikis_tarihi,sure,kategori,aciklama
532,81105406,TV Show,Monzón: A Knockout Blow,NaN,"Jorge Román, Mauricio Paniagua, Carla Quevedo,...",Argentina,"October 25, 2019",2018,1 Season,"Crime TV Shows, International TV Shows, Spanis...",This dramatization tells the story of Argentin...
6210,80239700,TV Show,Psiconautas,NaN,"Guillermo Toledo, Gabriel Goity, Florencia Peñ...",Argentina,"April 15, 2018",2016,2 Seasons,"International TV Shows, Spanish-Language TV Sh...",A Spanish con man masquerades as a therapist a...
4075,80156767,Movie,La Última Fiesta,"Leandro Mark, Nicolás Silbert","Nicolás Vázquez, Alan Sabbagh, Benjamín Amadeo...",Argentina,"February 1, 2017",2016,104 min,"Comedies, International Movies",Three best buddies are thrown into a wild chas...
398,80190990,Movie,Todo Sobre El Asado,"Mariano Cohn, Gastón Duprat",El Negro Álvarez,Argentina,"September 1, 2017",2016,86 min,"Documentaries, International Movies",This quirky examination of Argentina's culture...
4422,80142140,Movie,Daemonium,Pablo Parés,"Walter Cornás, Dany Casco, Caro Angus, Rocío R...",Argentina,"December 20, 2016",2015,115 min,"Action & Adventure, Horror Movies, Internation...",In a realm where magic and technology intersec...
...,...,...,...,...,...,...,...,...,...,...,...
6170,80136456,TV Show,Age of Glory,NaN,"Debbie Goh, Aenie Wong, Frederick Lee, Leslie ...",NaN,"August 14, 2017",2010,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Amid the thriving nightlife of 1960s Kuala Lum...
6195,80136790,TV Show,Goodnight DJ 1,NaN,"Chan Fong, Z-Chen, Frederick Lee, Melvin Sia, ...",NaN,"April 27, 2018",2016,2 Seasons,"International TV Shows, TV Dramas, TV Horror",Young radio announcers from varying background...
6199,80244228,TV Show,Beauty and the Bitches,NaN,"Methinee Kingpayome, Son Songpaisarn, Yingying...",NaN,"April 23, 2019",2016,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Beauty pageant contestants from all over Thail...
6228,80159925,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,2010,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,NaN,2016,60 min,Movies,Nursery rhymes and original music for children...